---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории.
  - Пользователь должен иметь возможность фильтровать товары по цене.
  - Пользователь должен иметь возможность фильтровать товары по цвету.
  - Пользователь должен иметь возможность фильтровать товары по размеру.
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре.
  - Пользователь должен иметь возможность добавлять товары в корзину.
  - Пользователь должен иметь возможность просматривать содержимое корзины.
non-functional:
  - Веб-сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы.
  - Сайт должен быть безопасным и защищать данные пользователя.
  - Сайт должен иметь мобильную версию.
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров.
  - Сайт должен быть способен обрабатывать большое количество трафика.
  - Сайт должен быть доступен на различных устройствах.
implicit:
  - Сайт должен быть SPA веб-приложением.
  - Корзина должна храниться в сессии браузера.
  - Сайт должен быть на русском и английском языках.
  - Пользователь должен иметь возможность удалить товар из корзины.
  - Пользователь должен иметь возможность продолжить выбирать товары в каталоге.
  - Пользователь должен иметь возможность оформить заказ с переходом на страницу оплаты.
